<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Microsite extends \Microsite implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIdmicrosite()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["idmicrosite"];
        }
        $this->__load();
        return parent::getIdmicrosite();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function getCierre()
    {
        $this->__load();
        return parent::getCierre();
    }

    public function setCierre($cierre)
    {
        $this->__load();
        return parent::setCierre($cierre);
    }

    public function getLogo()
    {
        $this->__load();
        return parent::getLogo();
    }

    public function setLogo($logo)
    {
        $this->__load();
        return parent::setLogo($logo);
    }

    public function getApertura()
    {
        $this->__load();
        return parent::getApertura();
    }

    public function setApertura($apertura)
    {
        $this->__load();
        return parent::setApertura($apertura);
    }

    public function setTitle($title)
    {
        $this->__load();
        return parent::setTitle($title);
    }

    public function getTitle()
    {
        $this->__load();
        return parent::getTitle();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setUrl($url)
    {
        $this->__load();
        return parent::setUrl($url);
    }

    public function getUrl()
    {
        $this->__load();
        return parent::getUrl();
    }

    public function setLogoprincipal($logoprincipal)
    {
        $this->__load();
        return parent::setLogoprincipal($logoprincipal);
    }

    public function getLogoprincipal()
    {
        $this->__load();
        return parent::getLogoprincipal();
    }

    public function setImagenslider($imagenslider)
    {
        $this->__load();
        return parent::setImagenslider($imagenslider);
    }

    public function getImagenslider()
    {
        $this->__load();
        return parent::getImagenslider();
    }

    public function setDireccion($direccion)
    {
        $this->__load();
        return parent::setDireccion($direccion);
    }

    public function getDireccion()
    {
        $this->__load();
        return parent::getDireccion();
    }

    public function setPuntogoogle($puntogoogle)
    {
        $this->__load();
        return parent::setPuntogoogle($puntogoogle);
    }

    public function getPuntogoogle()
    {
        $this->__load();
        return parent::getPuntogoogle();
    }

    public function setPagina($pagina)
    {
        $this->__load();
        return parent::setPagina($pagina);
    }

    public function getPagina()
    {
        $this->__load();
        return parent::getPagina();
    }

    public function setTelefono($telefono)
    {
        $this->__load();
        return parent::setTelefono($telefono);
    }

    public function getTelefono()
    {
        $this->__load();
        return parent::getTelefono();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setIdioma($idioma)
    {
        $this->__load();
        return parent::setIdioma($idioma);
    }

    public function getIdioma()
    {
        $this->__load();
        return parent::getIdioma();
    }

    public function setIdbase($idbase)
    {
        $this->__load();
        return parent::setIdbase($idbase);
    }

    public function getIdbase()
    {
        $this->__load();
        return parent::getIdbase();
    }

    public function setPredeterminado($predeterminado)
    {
        $this->__load();
        return parent::setPredeterminado($predeterminado);
    }

    public function getPredeterminado()
    {
        $this->__load();
        return parent::getPredeterminado();
    }

    public function setEstatus($estatus)
    {
        $this->__load();
        return parent::setEstatus($estatus);
    }

    public function getEstatus()
    {
        $this->__load();
        return parent::getEstatus();
    }

    public function setCreado($creado)
    {
        $this->__load();
        return parent::setCreado($creado);
    }

    public function getCreado()
    {
        $this->__load();
        return parent::getCreado();
    }

    public function addCategoriafk(\Categoria $categoriafk)
    {
        $this->__load();
        return parent::addCategoriafk($categoriafk);
    }

    public function removeCategoriafk(\Categoria $categoriafk)
    {
        $this->__load();
        return parent::removeCategoriafk($categoriafk);
    }

    public function getCategoriafk()
    {
        $this->__load();
        return parent::getCategoriafk();
    }

    public function addUser(\User $user)
    {
        $this->__load();
        return parent::addUser($user);
    }

    public function removeUser(\User $user)
    {
        $this->__load();
        return parent::removeUser($user);
    }

    public function getUser()
    {
        $this->__load();
        return parent::getUser();
    }

    public function addIdmarca(\Marca $idmarca)
    {
        $this->__load();
        return parent::addIdmarca($idmarca);
    }

    public function removeAllCategorias()
    {
        $this->__load();
        return parent::removeAllCategorias();
    }

    public function removeIdmarca(\Marca $idmarca)
    {
        $this->__load();
        return parent::removeIdmarca($idmarca);
    }

    public function getIdmarca()
    {
        $this->__load();
        return parent::getIdmarca();
    }

    public function setIduser(\User $iduser = NULL)
    {
        $this->__load();
        return parent::setIduser($iduser);
    }

    public function getIduser()
    {
        $this->__load();
        return parent::getIduser();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'idmicrosite', 'nombre', 'logoprincipal', 'imagenslider', 'direccion', 'puntogoogle', 'pagina', 'telefono', 'email', 'descripcion', 'idioma', 'idbase', 'predeterminado', 'estatus', 'creado', 'logo', 'apertura', 'cierre', 'title', 'description', 'url', 'categoriafk', 'user', 'idmarca', 'iduser');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}