<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class User extends \User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getIduser()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["iduser"];
        }
        $this->__load();
        return parent::getIduser();
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setNivelusuario($nivelusuario)
    {
        $this->__load();
        return parent::setNivelusuario($nivelusuario);
    }

    public function getNivelusuario()
    {
        $this->__load();
        return parent::getNivelusuario();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setEstatus($estatus)
    {
        $this->__load();
        return parent::setEstatus($estatus);
    }

    public function getEstatus()
    {
        $this->__load();
        return parent::getEstatus();
    }

    public function setCreado($creado)
    {
        $this->__load();
        return parent::setCreado($creado);
    }

    public function getCreado()
    {
        $this->__load();
        return parent::getCreado();
    }

    public function setFoto($foto)
    {
        $this->__load();
        return parent::setFoto($foto);
    }

    public function getFoto()
    {
        $this->__load();
        return parent::getFoto();
    }

    public function addMicrosite(\Microsite $microsite)
    {
        $this->__load();
        return parent::addMicrosite($microsite);
    }

    public function removeMicrosite(\Microsite $microsite)
    {
        $this->__load();
        return parent::removeMicrosite($microsite);
    }

    public function getMicrosite()
    {
        $this->__load();
        return parent::getMicrosite();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'iduser', 'username', 'email', 'nivelusuario', 'password', 'estatus', 'foto', 'creado', 'microsite');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}